name: build-wasm

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) + wasm target
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Build for wasm
        run: cargo build --release --target wasm32-unknown-unknown

      - name: List build output
        run: ls -lah target/wasm32-unknown-unknown/release

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: target/wasm32-unknown-unknown/release/*.wasm
          
