name: build-wasm

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) + wasm target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Build release WASM
        run: cargo build --release --target wasm32-unknown-unknown

      - name: List target folder
        run: ls -R target/wasm32-unknown-unknown/release

      - name: Upload WASM
        uses: actions/upload-artifact@v3
        with:
          name: uomi-telegram-agent
          path: target/wasm32-unknown-unknown/release/uomi-telegram-agent.wasm
          
